/*
 * Agent Protocol
 * Specification of the API protocol for communication with an agent.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package agentprotocol.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;
import agentprotocol.micronaut.model.Artifact;
import agentprotocol.micronaut.model.Pagination;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Introspected;
import agentprotocol.micronaut.invoker.annotation.HardNullable;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * TaskArtifactsListResponse
 */
@Serdeable
@JsonPropertyOrder({
    TaskArtifactsListResponse.JSON_PROPERTY_ARTIFACTS,
    TaskArtifactsListResponse.JSON_PROPERTY_PAGINATION
})
@Generated(value = "io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Introspected
public class TaskArtifactsListResponse {

    public static final String JSON_PROPERTY_ARTIFACTS = "artifacts";
    public static final String JSON_PROPERTY_PAGINATION = "pagination";

    @NotNull
    @Schema(name = "artifacts", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_ARTIFACTS)
    private List<Artifact> artifacts;

    @NotNull
    @Valid
    @Schema(name = "pagination", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_PAGINATION)
    private Pagination pagination;

    public TaskArtifactsListResponse(List<Artifact> artifacts, Pagination pagination) {
        this.artifacts = artifacts;
        this.pagination = pagination;
    }

    /**
     * @return the artifacts property value
     */
    public List<Artifact> getArtifacts() {
        return artifacts;
    }

    /**
     * Set the artifacts property value
     */
    public void setArtifacts(List<Artifact> artifacts) {
        this.artifacts = artifacts;
    }

    /**
     * Set artifacts in a chainable fashion.
     * @return The same instance of TaskArtifactsListResponse for chaining.
     */
    public TaskArtifactsListResponse artifacts(List<Artifact> artifacts) {
        this.artifacts = artifacts;
        return this;
    }

    /**
     * Add an item to the artifacts property in a chainable fashion.
     * @return The same instance of TaskArtifactsListResponse for chaining.
     */
    public TaskArtifactsListResponse addArtifactsItem(Artifact artifactsItem) {
        this.artifacts.add(artifactsItem);
        return this;
    }

    /**
     * @return the pagination property value
     */
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Set the pagination property value
     */
    public void setPagination(Pagination pagination) {
        this.pagination = pagination;
    }

    /**
     * Set pagination in a chainable fashion.
     * @return The same instance of TaskArtifactsListResponse for chaining.
     */
    public TaskArtifactsListResponse pagination(Pagination pagination) {
        this.pagination = pagination;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TaskArtifactsListResponse taskArtifactsListResponse = (TaskArtifactsListResponse) o;
        return Objects.equals(this.artifacts, taskArtifactsListResponse.artifacts) &&
            Objects.equals(this.pagination, taskArtifactsListResponse.pagination);
    }

    @Override
    public int hashCode() {
        return Objects.hash(artifacts, pagination);
    }

    @Override
    public String toString() {
        return "TaskArtifactsListResponse("
            + "artifacts: " + getArtifacts() + ", "
            + "pagination: " + getPagination()
            + ")";
    }

}