/*
 * Agent Protocol
 * Specification of the API protocol for communication with an agent.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package agentprotocol.micronaut.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;
import agentprotocol.micronaut.model.Pagination;
import agentprotocol.micronaut.model.Step;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.*;
import io.micronaut.serde.annotation.Serdeable;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;
import io.micronaut.core.annotation.Introspected;
import agentprotocol.micronaut.invoker.annotation.HardNullable;
import jakarta.annotation.Generated;
import io.swagger.v3.oas.annotations.media.Schema;

/**
 * TaskStepsListResponse
 */
@Serdeable
@JsonPropertyOrder({
    TaskStepsListResponse.JSON_PROPERTY_STEPS,
    TaskStepsListResponse.JSON_PROPERTY_PAGINATION
})
@Generated(value = "io.micronaut.openapi.generator.JavaMicronautServerCodegen")
@Introspected
public class TaskStepsListResponse {

    public static final String JSON_PROPERTY_STEPS = "steps";
    public static final String JSON_PROPERTY_PAGINATION = "pagination";

    @NotNull
    @Schema(name = "steps", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_STEPS)
    private List<Step> steps;

    @NotNull
    @Valid
    @Schema(name = "pagination", requiredMode = Schema.RequiredMode.REQUIRED)
    @JsonProperty(JSON_PROPERTY_PAGINATION)
    private Pagination pagination;

    public TaskStepsListResponse(List<Step> steps, Pagination pagination) {
        this.steps = steps;
        this.pagination = pagination;
    }

    /**
     * @return the steps property value
     */
    public List<Step> getSteps() {
        return steps;
    }

    /**
     * Set the steps property value
     */
    public void setSteps(List<Step> steps) {
        this.steps = steps;
    }

    /**
     * Set steps in a chainable fashion.
     * @return The same instance of TaskStepsListResponse for chaining.
     */
    public TaskStepsListResponse steps(List<Step> steps) {
        this.steps = steps;
        return this;
    }

    /**
     * Add an item to the steps property in a chainable fashion.
     * @return The same instance of TaskStepsListResponse for chaining.
     */
    public TaskStepsListResponse addStepsItem(Step stepsItem) {
        this.steps.add(stepsItem);
        return this;
    }

    /**
     * @return the pagination property value
     */
    public Pagination getPagination() {
        return pagination;
    }

    /**
     * Set the pagination property value
     */
    public void setPagination(Pagination pagination) {
        this.pagination = pagination;
    }

    /**
     * Set pagination in a chainable fashion.
     * @return The same instance of TaskStepsListResponse for chaining.
     */
    public TaskStepsListResponse pagination(Pagination pagination) {
        this.pagination = pagination;
        return this;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TaskStepsListResponse taskStepsListResponse = (TaskStepsListResponse) o;
        return Objects.equals(this.steps, taskStepsListResponse.steps) &&
            Objects.equals(this.pagination, taskStepsListResponse.pagination);
    }

    @Override
    public int hashCode() {
        return Objects.hash(steps, pagination);
    }

    @Override
    public String toString() {
        return "TaskStepsListResponse("
            + "steps: " + getSteps() + ", "
            + "pagination: " + getPagination()
            + ")";
    }

}